### ISSUE TITLE
Error: No default engine was specified and no extension was provided.

### ISSUE THREAD

**Issue by Kalle801** [Moorad/youtubeDownloader#22]
I installed it but i get this error: 
`Error: No default engine was specified and no extension was provided.
    at new View (C:\youtubeDownloader\Server\node_modules\express\lib\view.js:61:11)
    at Function.render (C:\youtubeDownloader\Server\node_modules\express\lib\application.js:570:12)
    at ServerResponse.render (C:\youtubeDownloader\Server\node_modules\express\lib\response.js:1012:7)
    at app.get (C:\youtubeDownloader\Server\index.js:54:5)
    at Layer.handle [as handle_request] (C:\youtubeDownloader\Server\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\youtubeDownloader\Server\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\youtubeDownloader\Server\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\youtubeDownloader\Server\node_modules\express\lib\router\layer.js:95:5)
    at C:\youtubeDownloader\Server\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (C:\youtubeDownloader\Server\node_modules\express\lib\router\index.js:335:12)`

**Comment by Moorad** [comment]
I'm not really sure why you are getting this error but it seems like you are trying to serve a file or use `app.set`/`app.use` without a view engine or something of that sort. Can you show me your code?
