### ISSUE TITLE
Error: Error parsing info: Unexpected token ) in JSON at position 0

### ISSUE THREAD

**Issue by Maks1116** [Moorad/youtubeDownloader#40]
When I try to download mp3 file I get this error on express
```
Error: Error parsing info: Unexpected token ) in JSON at position 0
    at exports.getBasicInfo (C:\Users\Maks_\Downloads\youtubeDownloader-master\Server\node_modules\ytdl-core\lib\info.js:71:11)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Map.getOrSet (C:\Users\Maks_\Downloads\youtubeDownloader-master\Server\node_modules\ytdl-core\lib\cache.js:24:19)
    at async C:\Users\Maks_\Downloads\youtubeDownloader-master\Server\index.js:21:3
```

**Comment by andrewip1027** [comment]
same exact error

**Comment by andrewip1027** [comment]
this is a library error, no easy fix.

**Comment by OmarHopman** [comment]
I'm having the same issue.

**Comment by anpinghuang** [comment]
same error
